name: Delete Old ECR Images

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
 cleanup-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh
      
      - name: Authenticate with GitHub CLI
        run: gh auth login
      
      # Now you can use the GitHub CLI in subsequent steps
      - name: List GitHub releases
        run: gh release list

      - name: Install jq for JSON parsing
        run: sudo apt-get install jq -y

      - name: Delete Old Workflow Runs
        env:
          WORKFLOW_FILE: "0-welcome.yml" 
          DAYS_TO_KEEP: "2"
        run: |
          #!/bin/bash
          set -e

          workflow_file="${WORKFLOW_FILE}"
          days_to_keep="${DAYS_TO_KEEP}"

          # Calculate cutoff date (runs older than this will be deleted)
          cutoff_date=$(date -d "$days_to_keep days ago" +%Y-%m-%dT%H:%M:%SZ)

          echo "Cutoff date for deleting workflow runs: $cutoff_date"

          # List all workflow runs for the specified workflow file, limited to 100
          echo "Listing all workflow runjobs:s for $workflow_file:"
          gh run list --limit 100 --workflow=$workflow_file --json databaseId,createdAt | \
            jq -r --arg cutoff "$cutoff_date" '.[] | select(.createdAt < $cutoff) | .databaseId' > runs_to_delete.txt

          # Check if there are any runs to delete
          if [ ! -s runs_to_delete.txt ]; then
            echo "No workflow runs older than $days_to_keep days to delete."
          else
            echo "Deleting the following workflow runs:"
            cat runs_to_delete.txt

            # Delete each workflow run found
            cat runs_to_delete.txt | xargs -I{} gh run delete {}

            echo "Deletion complete."
          fi
